subject=["C","C++","Java","C#","HTML"]
number=[500,5,900,0,999,7]
number.reverse()
number.pop()
print(number)
print(number)
subject.append("TOC")
print(subject)
print(subject[1])
print(subject[-2])
print(subject[:2])
print(subject[2:])
print("C" in subject)
print("K" in subject)
print("K" not in subject)
print(subject +["K++",10])
print(len(subject))
subject.insert(2,"OS")
print(subject)
subject.remove("OS")
print(subject)
subject.sort()
print(subject)
